Numpy

In this jupiter notebook i'll tell you how Numpy works in python

In [2]:
import numpy as np

### numpy array

In [40]:
arr_1D = np.array([1, 2, 3])
print("Numpy 1D array: \n", arr_1D )

arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
print("Numpy 2D array: \n", arr_2D)

Numpy 1D array: 
 [1 2 3]
Numpy 2D array: 
 [[1 2 3]
 [4 5 6]]


In [6]:
py_list = [1, 2, 3]
print("Python list",py_list * 2)

numpy_arr = np.array([1, 2, 3])
print("Numpy array",numpy_arr * 2)

Python list [1, 2, 3, 1, 2, 3]
Numpy array [2 4 6]


### Difference between python list and python array

In [35]:
import time
start = time.time()
py_list = [i *2 for i in range(1000000)]
print(" \n Python list Operaional time: ", time.time()-start)

start = time.time()
numpy_arr = np.arange(1000000)*2
print(" \n Python array Operational time: ", time.time()-start)

 
 Python list Operaional time:  0.2448885440826416
 
 Python array Operational time:  0.011539697647094727


In [36]:
zeros = np.zeros((3,5))
print("Zeros of Array: \n", zeros)

Zeros of Array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
once = np.ones((3,4))
print("Once of array: \n", once)

Once of array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Custom Array

In [39]:
full = np.full((2,4), 5)
print("Full array: \n", full)

Full array: 
 [[5 5 5 5]
 [5 5 5 5]]


Random array

In [52]:
random_arr = np.random.random((2,3))
print(random_arr)

[[0.17561372 0.01868398 0.66636167]
 [0.10778269 0.42444893 0.47868104]]


In [54]:

sequence_array = np.arange(1, 11, 2)
print("Sequence array: \n", sequence_array)

Sequence array: 
 [1 3 5 7 9]


### Vector, Matrix and tensor

In [90]:
vector = np.array([1, 3, 8])
print("Vector \n", vector)

matrix = np.array([[1, 2, 3],
                   [4, 8, 3]])
print("\n Matrix \n", matrix)


tensor = np.array([[[1, 7],[ 8, 4]],
                   [[2, 6], [7, 3]]])
print("\n Tensor \n", tensor)



Vector 
 [1 3 8]

 Matrix 
 [[1 2 3]
 [4 8 3]]

 Tensor 
 [[[1 7]
  [8 4]]

 [[2 6]
  [7 3]]]


### Numpy Properties

In [74]:
arr = np.array([[1, 5, 9],
                [3, 7, 9],
                [4, 7, 2]])
print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Dimention", arr.ndim)
print("Size (Number of elements)", arr.size)
print("Data Type", arr.dtype)

Array: 
 [[1 5 9]
 [3 7 9]
 [4 7 2]]
Shape:  (3, 3)
Dimention 2
Size (Number of elements) 9
Data Type int64


Reshape of Array

In [105]:
arr = np.arange(12)
print("Array: \n", arr)


reshaped = arr.reshape((4, 3))
print("\n Reshaped array \n", reshaped)

transposed = reshaped.T
print("\n Tranposed array: \n", transposed)

flattened = reshaped.flatten()
print("\n Flattened Array: ", flattened)
#For checking
flattened[0] = 100
print(arr)

# Ravel(returns View Instead of Copy)
raveled = reshaped.ravel()
print("\n Raveled Array: ", raveled)
#For checking
raveled[0] = 200
print(arr)


Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 Tranposed array: 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
[200   1   2   3   4   5   6   7   8   9  10  11]


### Numpy array opertaions

In [132]:

arr = np.array([[1, 5, 7],
                [4, 8, 10],
                [5, 9, 3]])
print("Array: \n", arr)
print("\n Dimention of that array: ", arr.ndim)


print("\n Specific Element: ", arr[1, 1])
print("\n Specific Row of that Array: ", arr[1])
print("\n Specific Column of that array which shows in row: ",arr[:, 2] )
print("\n Tranpose of that array \n", arr.T)


Array: 
 [[ 1  5  7]
 [ 4  8 10]
 [ 5  9  3]]

 Dimention of that array:  2

 Specific Element:  8

 Specific Row of that Array:  [ 4  8 10]

 Specific Column of that array which shows in row:  [ 7 10  3]

 Tranpose of that array 
 [[ 1  4  5]
 [ 5  8  9]
 [ 7 10  3]]


### Slicing of array

In [140]:
arr = np.arange(1, 11)
print("\n Array: ",arr)
print("\n Basic slicing: ",arr[4:7])
print("\n With Step: ", arr[1::2])
print("\n negative slicing: ", arr[-4: ])



 Array:  [ 1  2  3  4  5  6  7  8  9 10]

 Basic slicing:  [5 6 7]

 With Step:  [ 2  4  6  8 10]

 negative slicing:  [ 7  8  9 10]


### Sorted array

In [144]:
unsorted_arr = np.array([1, 7, 5, 3, 1, 8, 10, 3, 7, 9])
print("Sorted Array: ", np.sort(unsorted_arr))

unsorted_2D_array = np.array([[1, 4, 8],
                              [5, 7, 2],
                              [4, 9, 4],
                              [6, 0, 3]])
print("\n Sorted 2D Array by Column: \n", np.sort(unsorted_2D_array, axis = 0))
print("\n Sorted 2D Array by rows \n", np.sort(unsorted_2D_array, axis = 1) )

Sorted Array:  [ 1  1  3  3  5  7  7  8  9 10]

 Sorted 2D Array by Column: 
 [[1 0 2]
 [4 4 3]
 [5 7 4]
 [6 9 8]]

 Sorted 2D Array by rows 
 [[1 4 8]
 [2 5 7]
 [4 4 9]
 [0 3 6]]


## Filter

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = arr[arr % 2 == 0]
print("Even numbers Array: ",even_numbers)

mask = arr > 5
print("Array numbers greater than 5: ",arr[mask])

Even numbers Array:  [ 2  4  6  8 10]
Array numbers greater than 5:  [ 6  7  8  9 10]


In [11]:

indices = [0, 5, 7]
print(arr[indices])

where_result = np.where(arr > 5)
print(where_result)
print(arr[where_result])

[1 6 8]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [13]:
conditional_array = np.where(arr > 5, arr * 2, arr)
print("Conditional Array: ", conditional_array)

Conditional Array:  [ 1  2  3  4  5 12 14 16 18 20]
